telethon:
  user_id: 0
  logged_in: false
download_path: C:/Users
language: en
theme: light
view_mode: icon
clipboard_enabled: true
upload_retry_times: 3
max_concurrent_uploads: 3
upload_limit_settings:
  enabled: true
  max_daily_size_gb: 200.0
  max_daily_files: 800
  max_single_file_size_gb: 1.8
  reset_hour: 0
auto_sync_settings:
  enabled: false
  folders:

